# Generated by Django 3.0.8 on 2021-04-15 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210416_0105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='products.Product'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('title', 'slug')},
        ),
    ]
