# Generated by Django 3.0.8 on 2021-04-16 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20210416_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('product', 'slug')},
        ),
    ]
